stages:
  - test
  - build
  - deploy

#image: johnpapa/angular-cli
image: node:latest

cache:
  paths:
    - dist/
    - node_modules/

test:
  stage: test
  script:
    - npm i
    - npm run test

build:
  stage: build
  script:
    - npm install
    - ./node_modules/@angular/cli/bin/ng build --prod
  artifacts:
    paths:
      - dist
  when: on_success
  dependencies:
    - test

setup-deploy:
  image: tsuru/client:latest
  stage: deploy
  when: manual
  script:
    - tsuru app-create ${CI_PROJECT_NAME}-staging static
    - tsuru app-create ${CI_PROJECT_NAME}-production static

.job_template: &deploy_definition
  image: tsuru/client:latest
  stage: deploy
  when: manual
  script:
    - cd dist
    - tsuru app-deploy -a ${CI_PROJECT_NAME}-${DEPLOY_MODE} .
  dependencies:
    - build
  environment:
    name: ${DEPLOY_MODE}

deploy-staging-tsuru:
  <<: *deploy_definition
  only:
    - developer
  variables:
    DEPLOY_MODE: staging

deploy-production-tsuru:
  <<: *deploy_definition
  only:
    - master
  variables:
    DEPLOY_MODE: production
